spring.application.name=test-spring-boot-app-for-working
logging.level.root[0]=info
logging.level.root[1]=debug
# config by java code
#spring.datasource.url=jdbc:sqlserver://GA003892-IN0001;database=TTKNP;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=ttknp
#spring.datasource.password=Arch.890.098
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto = none

# error when i try to get bean service (getBean(<By Class>))
# fix The bean 'dataSourceMySQLExtraA', defined in class path resource [xml/spring-context-mysql-extra-a-database.xml], could not be registered.
spring.main.allow-bean-definition-overriding=true