TRUNCATE TABLE TTKNP.A_APP.USERS_DETAIL;

INSERT INTO TTKNP.A_APP.USERS_DETAIL (ID, FIRSTNAME, LASTNAME, AGE, EMAIL, PHONE) VALUES (1, 'Alex', 'Ryder', 52, 'Alex@hotmail.com', '0898989898');
INSERT INTO TTKNP.A_APP.USERS_DETAIL (ID, FIRSTNAME, LASTNAME, AGE, EMAIL, PHONE) VALUES (2, 'Jack', 'Ryder', 43, 'Jack@hotmail.co', '0989898584');
INSERT INTO TTKNP.A_APP.USERS_DETAIL (ID, FIRSTNAME, LASTNAME, AGE, EMAIL, PHONE) VALUES ({ID}, {FIRSTNAME}, {LASTNAME}, {AGE}, {EMAIL}, {PHONE});


