INSERT INTO A_APP.USERS_DETAIL_BAK (ID,FIRSTNAME,LASTNAME,AGE,EMAIL,PHONE)
 SELECT ID,FIRSTNAME,LASTNAME,AGE,[EMAIL],PHONE
  FROM A_APP.USERS_DETAIL
   WHERE ID = {ID};
-- [] is optional parameter(s) & {} is required parameter(s)
